// Generated by CoffeeScript 1.6.3
(function() {
  define(["dojo/_base/declare", "dgrid/OnDemandGrid", "dgrid/Keyboard", "dgrid/extensions/ColumnResizer", "dgrid/Selection", "dgrid/extensions/DijitRegistry"], function(declare, OnDemandGrid, Keyboard, ColumnResizer, Selection, DijitRegistry) {
    return declare([OnDemandGrid, Selection, Keyboard, ColumnResizer, DijitRegistry]);
  });

}).call(this);
